import 'package:food_delivery/core/constants/paths.dart';
import 'package:food_delivery/shared/models/restaurant_entity.dart';
import 'package:food_delivery/shared/models/meal_entity.dart';

final allMeals = dummyRestaurants.expand((r) => r.meals).toList();

final dummyRestaurants = <RestaurantEntity>[
  RestaurantEntity(
    name: 'Burger House',
    description: 'Lezzetli ve doyurucu burgerler',
    rating: 4.5,
    deliveryType: 'Ücretsiz',
    deliveryTime: '25-35 dk',
    imageUrl: AppPaths.burgerHouse,
    meals: [
      MealEntity(
        name: 'Cheeseburger',
        restaurantName: 'Burger House',
        description:
            'Dana eti, cheddar peyniri, turşu, özel sos ve ekmek ile hazırlanmıştır.\n',
        rating: 4.6,
        delivery: 'Ücretsiz',
        deliveryTime: '25-35 dk',
        size: 'Normal',
        category: 'Burger',
        ingredients: ['Dana eti', 'Cheddar', 'Turşu', 'Sos', 'Ekmek'],
        imageUrl: AppPaths.cheeseburger,
        price: '9.99',
      ),
      MealEntity(
        name: 'Double Burger',
        restaurantName: 'Burger House',
        description: 'İki kat dana eti, ekstra peynir',
        rating: 4.7,
        delivery: '₺9.99',
        deliveryTime: '30-40 dk',
        size: 'Büyük',
        category: 'Burger',
        ingredients: ['Dana eti', 'Cheddar', 'Marul', 'Sos', 'Ekmek'],
        imageUrl: AppPaths.doubleBurger,
        price: '12.99',
      ),
    ],
  ),
  RestaurantEntity(
    name: 'Pizza King',
    description: 'Odun ateşinde nefis pizzalar',
    rating: 4.8,
    deliveryType: '₺5.99',
    deliveryTime: '30-40 dk',
    imageUrl: AppPaths.pizzaKing,
    meals: [
      MealEntity(
        name: 'Karışık Pizza',
        restaurantName: 'Pizza King',
        description: 'Sucuk, mantar, biber, zeytin, mozarella',
        rating: 4.9,
        delivery: '₺5.99',
        deliveryTime: '30-40 dk',
        size: 'Medium',
        category: 'Pizza',
        ingredients: ['Sucuk', 'Mantar', 'Zeytin', 'Peynir', 'Domates sos'],
        imageUrl: AppPaths.mixedPizza,
        price: '11.99',
      ),
    ],
  ),
  RestaurantEntity(
    name: 'Sushi Go',
    description: 'Taptaze Japon mutfağı',
    rating: 4.6,
    deliveryType: 'Ücretsiz',
    deliveryTime: '20-30 dk',
    imageUrl: AppPaths.sushiGo,
    meals: [
      MealEntity(
        name: 'California Roll',
        restaurantName: 'Sushi Go',
        description: 'Yengeç eti, avokado, salatalık',
        rating: 4.4,
        delivery: 'Ücretsiz',
        deliveryTime: '20-30 dk',
        size: '8 Parça',
        category: 'Sushi',
        ingredients: ['Yengeç', 'Avokado', 'Salatalık', 'Pirinç', 'Nori'],
        imageUrl: AppPaths.californiaRoll,
        price: '14.99',
      ),
    ],
  ),
  RestaurantEntity(
    name: 'Taco Max',
    description: 'Baharatlı Meksika lezzetleri',
    rating: 4.3,
    deliveryType: '₺4.99',
    deliveryTime: '25-35 dk',
    imageUrl: AppPaths.tacoMax,
    meals: [
      MealEntity(
        name: 'Beef Taco',
        restaurantName: 'Taco Max',
        description: 'Dana kıyma, salsa sos, yeşillik',
        rating: 4.2,
        delivery: '₺4.99',
        deliveryTime: '25-35 dk',
        size: '2 Adet',
        category: 'Taco',
        ingredients: ['Dana eti', 'Salsa', 'Marul', 'Tortilla'],
        imageUrl: AppPaths.beefTaco,
        price: '8.99',
      ),
    ],
  ),
  RestaurantEntity(
    name: 'Kebabçi Ali',
    description: 'Geleneksel Türk mutfağı',
    rating: 4.7,
    deliveryType: 'Ücretsiz',
    deliveryTime: '30-40 dk',
    imageUrl: AppPaths.kebabciAli,
    meals: [
      MealEntity(
        name: 'Adana Kebap',
        restaurantName: 'Kebabçi Ali',
        description: 'Acılı dana eti, közlenmiş biber, lavaş',
        rating: 4.6,
        delivery: 'Ücretsiz',
        deliveryTime: '30-40 dk',
        size: 'Tek Porsiyon',
        category: 'Kebap',
        ingredients: ['Dana eti', 'Biber', 'Domates', 'Lavaş'],
        imageUrl: AppPaths.adanaKebap,
        price: '15.99',
      ),
    ],
  ),
];
